### PR TITLE
workaround with non-existing-key in my policy

### PR DESCRIPTION
**Pull request by pgastinger**
In my policy, 

```
[Expert@fwmgmt:0]# ./python import_export_package.py -d 10.xx.xx.xx -u
username -op export -ac -o policyexport --debug on -n TEST-FW
[..snip...]
Traceback (most recent call last):
  File "import_export_package.py", line 45, in <module>
    export_package(client, args)
  File
"/home/admin/ExportImportPolicyPackage-master/exporting/export_package.py",
line 38, in export_package
    = export_access_rulebase(show_package.data["name"],
access_layer["name"], client, timestamp, tar_file)
  File
"/home/admin/ExportImportPolicyPackage-master/exporting/export_access_rulebase.py",
line 16, in export_access_rulebase
    get_query_rulebase_data(client, "access-rulebase", {"name": layer,
"package": package})
  File
"/home/admin/ExportImportPolicyPackage-master/exporting/export_objects.py",
line 131, in get_query_rulebase_data
    section["to"] = rulebase_item["to"]
KeyError: 'to'
```

It look like it fails with an empty rulebase (print output of section and rulebase_item before exception:
```
{u'rulebase': [], u'type': u'access-section', u'uid': u'3604724a-675b-426b-88e2-2fa047a2be15', u'name': u'VPN-Tunnel: INS'}
{u'rulebase': [], u'type': u'access-section', u'uid': u'3604724a-675b-426b-88e2-2fa047a2be15', u'name': u'VPN-Tunnel: INS'}
```

Screenshot from my dashboard:
image

### CODE REVIEW

**Comment by CheckPoint-APIs-Team** [comment]
Hi,
Thanks a lot for your contribution!
If I understand this correctly, the problem happens when you have an empty rulebase with a single empty section?

**Comment by pgastinger** [comment]
Actually, the rule base is not empty (approx. 2000 rules). But there is an empty section and as far as I figured out, that's the reason for the exception. 

(I suppose there are better ways to solve this issue, e.g. check if the section is empty, but I have not enough time for better solutions ;-))

**Comment by CheckPoint-APIs-Team** [comment]
Thank you very much for your feedback. We really appreciate it.
We will examine this issue further and provide an appropriate solution.

**Comment by CheckPoint-APIs-Team** [comment]
Nice! We are working on NAT rulebase as well, will be delivered soon.
Stay tuned...

**Comment by CheckPoint-APIs-Team** [comment]
Hi Peter,
We indeed found and reproduced the problem.
It is enough to check for rulebase_item having "to" in its dictionary.
We will upload a fix shortly.
Thank you!

**Comment by CheckPoint-APIs-Team** [comment]
Uploaded the fix. Please use the new source code.
Thanks.

**Pull request closed without merging**
